### ISSUE TITLE
ykls panics when a non-YubiKey smartcard reader is present

### ISSUE THREAD

**Issue by nbraud** [go-piv/go-ykpiv#38]
The following occurs if I run `ykls` while my laptop's ExpressCard smartcard reader is in:

```
$ dpkg -x /opt/deb/buildarea/golang-pault-go-ykpiv-dev_1.3.2-1_amd64.deb .
$ ./usr/bin/ykls --help
Reader:  Gemalto GemPC Express 00 00
panic: ykpiv ykpiv_connect: PKCS Error (-2) - Error in PCSC call

goroutine 1 [running]:
main.ohshit(...)
	pault.ag/go/ykpiv/cmd/ykls/ykls.go:31
main.main()
	pault.ag/go/ykpiv/cmd/ykls/ykls.go:44 +0x7cd
```

After removing the reader: 
```
$ ./usr/bin/ykls 
Reader:  Yubico YubiKey FIDO+CCID 00 00
Version: 4.3.7
Serial:  6447364
Slot Authentication (9a): nicoo@debian.org
```

**Comment by LudovicRousseau** [comment]
I have the same problem and in my case the PC/SC reader is also my main keyboard. So I can't disconnect it.
```
$ ykls
Reader:  Cherry GmbH CHERRY SECURE BOARD 1.0 [CHERRY SECURE BOARD 1.0] (00000002JS0405948M3DOGKTHA) 00 00
panic: ykpiv ykpiv_connect: PKCS Error (-2) - Error in PCSC call

goroutine 1 [running]:
main.ohshit(...)
	pault.ag/go/ykpiv/cmd/ykls/ykls.go:31
main.main()
	pault.ag/go/ykpiv/cmd/ykls/ykls.go:44 +0x7cd
```
One workaround is to use `PCSCLITE_FILTER_IGNORE_READER_NAMES=` as documented in https://ludovicrousseau.blogspot.com/2015/12/remove-andor-customize-pcsc-reader-names.html

``` 
$ sudo PCSCLITE_FILTER_IGNORE_READER_NAMES=Cherry pcscd
$ ykls
Reader:  Yubico YubiKey OTP+FIDO+CCID 00 00
Version: 5.1.2
Serial:  9718408
```

A correct fix would be to ignore a PC/SC reader that do not contain a Yubikey and continue with the next reader in the list.
I guess the problem is this line https://github.com/go-piv/go-ykpiv/blob/master/cmd/ykls/ykls.go#L44

**Comment by LudovicRousseau** [comment]
I was about the report, again, the same bug. 
But I see it is a known issue since more than 2 years. And nothing happened.
It looks like it is a dead project :-(
